import logo from './getlinked.svg'
import menuBar from './menu.svg'
import circle from './circle.svg'
import x from './x.svg'
import light from './light.svg'
import bulb from './bulb.svg'
import chain from './chain.svg'
import star from './star.svg'
import underline from './underline.svg'
import spark from './spark.svg'
import purpleBg from './PurpleBg.svg'
import purpleBgRight from './PurpleBgRight.svg'
import introArrow from './introArrow.svg'
import purpleStar from './purpleStar.svg'
import questionMark from './questionMark.svg'
import LibertyAssured from './Liberty company logo white colour.svg'
import LibertyPay from './Liberty company logo white.svg'
import Winwise from './Winwise logo White colour 1.svg'
import Wisper from './wisper logo white.svg'
import PayBox from './Paybox.svg'
import Vuzual from './Vuzual Plus.svg'
import instagram from './mdi_instagram.svg'
import twitter from './twitter.svg'
import facebook from './facebook.svg'
import linkedin from './ri_linkedin-fill.svg'
import phone from './phone.svg'
import location from './location.svg'

export {
    logo, menuBar, circle, x, light, bulb, chain, star, underline, spark, purpleBg, purpleBgRight, introArrow, purpleStar, questionMark, LibertyAssured, LibertyPay, Winwise, Wisper, PayBox, Vuzual, instagram, twitter, facebook, linkedin, phone, location
}